data:
  raw_path: data/raw/pakistan_house_prices.csv    # rename if your file differs
  processed_path: data/processed/clean.csv
  features_path: data/features/Xy.joblib

split:
  test_size: 0.2
  random_state: 42

model:
  type: RandomForestRegressor
  n_estimators: 200
  max_depth: 12
  random_state: 42
